### PR TITLE
Use correct separator in keywords.txt

### PR DESCRIPTION
**Pull request by per1234**
The Arduino IDE requires the use of a tab separator between the name and identifier. Without this tab the keyword is not highlighted.

Reference: https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification#keywords

### CODE REVIEW

**Comment by per1234** [comment]
Please let me know if there's anything I need to do to get this pull request merged.

**Comment by drewfish** [comment]
Sorry, I lost track of this. Merged now.

**Comment by drewfish** [comment]
It's been a long time since I've used this library, let me know if there's something I need to do to get this into the IDE (somehow publish a new version?).

**Comment by per1234** [comment]
There is now a Library Manager feature in the Arduino IDE that allows people to search through a large, author-submitted, categorized, list of Arduino libraries and easily install them with a single click. Library Manager displays a notification when a new version of any installed library is released and makes it very easy to update to the new version. They can also chose to install any released version of the library, which can be useful for troubleshooting. Your library already meets all the requirements for Library Manager index inclusion except that you don't have any releases or tags. If you want it to the Library Manager you would only need to:

- Create a [release](https://help.github.com/articles/creating-releases/) or [tag](https://git-scm.com/docs/git-tag) that matches the [`version` value in your library.properties file](https://github.com/drewfish/arduino-ZeroRegs/blob/master/library.properties#L2) (currently 0.2.0).
- Submit an issue to https://github.com/arduino/Arduino/issues requesting your library to be added with a link to this repository.

For more information see:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

Let me know if you have any questions about this process. I'm fairly knowledgeable on the topic and happy to help.

**Comment by drewfish** [comment]
Cool thanks, I've cut [release 0.2.1](https://github.com/drewfish/arduino-ZeroRegs/releases/tag/0.2.1) and [submitted a request](https://github.com/arduino/Arduino/issues/7397).

**Comment by drewfish** [comment]
I found a bunch of commits I hadn't pushed, so rolled those into 0.2.1 also.

**Pull request merged**
